### PR TITLE
Add "Hello Microverse" feature

### PR DESCRIPTION
**Pull request by Pejoma2**
- Add index.html
- Add style.css linked with index.html
- Add Linters
- Add gitignore for node_modules/test.md

### CODE REVIEW

**Review by Gopxfs — CHANGES_REQUESTED** [review]
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi @Pejoma2 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights :rocket:
✔️ No linter errors.
✔️ Great code structure. Well done!
✔️ Nearly perfect first PR.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gopxfs** [comment]
Hello @Pejoma2, your first Pull Request looks almost perfect! Great job! The only change that I will propose to you is to update your title. As explained on [how to document your work in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md): 
image 

Please add a more meaningful title to your PR. This will make clearer what you are adding to your project and will be easier to keep track of your activities in the future 😄. 

My tip for you: try to think about what your feature is adding. Is it a section? What section? Try to be precise and clear with your PR titles. You could do something like this: _Add hello Microverse text_ or _Initial setup_. 

Overall, you did a pretty good job with your first PR 😉. Good luck and keep up the good work!

**Comment by Gopxfs** [comment]
[OPTIONAL] For your next descriptions and branch names, try to make them more direct. What was added in these HTML + CSS? Please make sure that anyone who reads your branch name/description understands what you implemented 😉.

**Review by frank1738 — APPROVED** [review]
Hi @Pejoma2 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Good PR Description👍

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
